/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Check if the server and database are healthy
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Server and database are healthy */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-3'];
          };
        };
        /** @description Database unreachable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-3'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List plans owned by user
     * @description Retrieve plans created by the authenticated user, ordered by creation date
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of plans owned by the authenticated user */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-6'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a plan with owner participant
     * @description Creates a plan and its owner participant in a single transaction. Requires JWT. Returns the plan with participants[] and items[].
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-10'];
        };
      };
      responses: {
        /** @description Plan created successfully with owner and participants */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-25'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/plans': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Admin: list all plans
     * @description Returns all plans in the system. Admin only. JWT required.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of all plans (admin only) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-6'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Forbidden — insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/pending-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List plans with pending join requests
     * @description Returns minimal plan details (planId, title, dates, location) for plans where the user has a pending join request. JWT required.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of plans with pending join requests for the user */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-8'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get plan preview
     * @description Returns minimal plan info when user is authed but not a participant (needs to create join request). JWT required. 400 if already a participant.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plan preview for non-participant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-27'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan does not exist or you do not have access */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get plan by ID
     * @description Returns full plan for participants, or preview+joinRequest for non-participants. JWT required.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Full plan for participants, or preview+joinRequest for non-participants */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json':
              | components['schemas']['def-25']
              | components['schemas']['def-31'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan does not exist or you do not have access */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a plan
     * @description Delete a plan by its ID. Requires JWT. Admin can delete any plan; owner can delete their own. Cascade delete handles related items, participants, and assignments.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plan deleted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-13'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan does not exist or you do not have access */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a plan
     * @description Update an existing plan by its ID
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-11'];
        };
      };
      responses: {
        /** @description Updated plan */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-5'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan does not exist or you do not have access */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
  '/plans/{planId}/participants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all participants for a plan
     * @description Retrieve all participants belonging to a specific plan
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of participants */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-20'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — participant or plan does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    /**
     * [UPDATED] Add a participant to a plan
     * @description Create a new participant in the specified plan. Required fields changed: now requires name, lastName, contactPhone instead of displayName.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-21'];
        };
      };
      responses: {
        /** @description Created participant */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-19'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — participant or plan does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/participants/{participantId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get participant by ID
     * @description Retrieve a single participant by its ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          participantId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Participant details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-19'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — participant or plan does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a participant
     * @description Delete a participant by its ID. Items assigned to this participant will have their assignment cleared.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          participantId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Participant deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-24'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — participant or plan does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a participant
     * @description Update an existing participant by its ID. Owner/admin can update any participant; linked participants can only update their own record.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          participantId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-22'];
        };
      };
      responses: {
        /** @description Updated participant */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-19'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Forbidden — insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — participant or plan does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
  '/plans/{planId}/participants/{participantId}/regenerate-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Regenerate invite token for a participant
     * @description Generates a new invite token for the specified participant, invalidating the previous one. Requires API key (owner action).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
          participantId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Regenerated invite token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-40'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — participant or plan does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all items for a plan
     * @description Retrieve all items belonging to a specific plan. Response filtering: owners see the full assignmentStatusList for each item; non-owners (participants) see only their own entry in assignmentStatusList. There is no top-level status field — check assignmentStatusList entries for per-participant status.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of items */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-15'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan or item does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    /**
     * Add an item to a plan
     * @description Create a new item (no top-level status field — per-participant status lives in assignmentStatusList). Equipment items always use pcs. Assignment fields (owner-only): send assignmentStatusList with participant entries (each has participantId + status) and isAllParticipants=true to assign all, or a subset with isAllParticipants=false. Omit both to create unassigned.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-16'];
        };
      };
      responses: {
        /** @description Created item */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-14'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan or item does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/items/{itemId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update an item
     * @description Update an item. No top-level status field — use assignmentStatusList to change per-participant status. Owner: send the full assignmentStatusList array (replaces existing) + isAllParticipants. Non-owner: send assignmentStatusList with ONLY your own entry (e.g. [{ participantId: "your-id", status: "purchased" }]) — the backend merges it into the full list, preserving other participants. Response: owners see the full assignmentStatusList; non-owners see only their own entry.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-17'];
        };
      };
      responses: {
        /** @description Updated item */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-14'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan or item does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
  '/plans/{planId}/items/bulk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk create items in a plan
     * @description Create multiple items at once. Each item is validated independently. No top-level status field — per-participant status lives in assignmentStatusList. Assignment fields (owner-only): send assignmentStatusList and isAllParticipants per item.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-46'];
        };
      };
      responses: {
        /** @description Bulk operation results — all succeeded */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-50'];
          };
        };
        /** @description Partial success — some items failed, check errors array */
        207: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-50'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan or item does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Bulk update items in a plan
     * @description Update multiple items at once. Each item is validated independently. No top-level status field — use assignmentStatusList per item. Owner: send the full assignmentStatusList (replaces). Non-owner: send only your own entry per item — backend merges. Response: non-owners see only their own entry in each item's assignmentStatusList.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-48'];
        };
      };
      responses: {
        /** @description Bulk operation results — all succeeded */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-50'];
          };
        };
        /** @description Partial success — some items failed, check errors array */
        207: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-50'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan or item does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
  '/plans/{planId}/invite/{inviteToken}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Access a plan via invite link
     * @description Public endpoint. Validates the invite token and returns plan data with items. Items are filtered to only those assigned to the guest or unassigned. Each item's assignmentStatusList is filtered to show only the guest's own entry. Participant PII is stripped — only displayName and role are included. There is no top-level status on items — check assignmentStatusList for per-participant status.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
          inviteToken: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plan and items returned for the invite token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-38'];
          };
        };
        /** @description Not found — plan, item, or invite token is invalid */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}/invite/{inviteToken}/preferences': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update guest preferences via invite token
     * @description Allows a guest to update their per-plan preferences (display name, group size, dietary info) using the invite token in the URL. All fields are optional — send only what changed. Send null to clear a field.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
          inviteToken: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-41'];
        };
      };
      responses: {
        /** @description Guest preferences updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-42'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan, item, or invite token is invalid */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
  '/plans/{planId}/invite/{inviteToken}/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an item as a guest via invite token
     * @description Creates a new item (no top-level status field). Equipment items default to pcs; food items require a unit. The item is not auto-assigned — send assignmentStatusList separately via PATCH if needed.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
          inviteToken: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-44'];
        };
      };
      responses: {
        /** @description Item created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-14'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan, item, or invite token is invalid */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}/invite/{inviteToken}/items/{itemId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update an item as a guest via invite token
     * @description Updates an existing item. Allowed if the item is assigned to the guest or unassigned. Returns 403 if assigned to a different participant. No top-level status field — to update your status, send assignmentStatusList with your own entry: [{ participantId: "your-id", status: "purchased" }]. Backend merges into the full list. Response returns assignmentStatusList filtered to only your entry.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
          inviteToken: string;
          itemId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-45'];
        };
      };
      responses: {
        /** @description Item updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-14'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Forbidden — insufficient permissions */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan, item, or invite token is invalid */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
  '/plans/{planId}/invite/{inviteToken}/items/bulk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk create items as a guest via invite token
     * @description Creates multiple items (no top-level status field). Each item is validated independently — valid items are created, invalid items are reported in the errors array. Items are not auto-assigned.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
          inviteToken: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-51'];
        };
      };
      responses: {
        /** @description All items created successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-50'];
          };
        };
        /** @description Partial success — some items created, some had validation errors */
        207: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-50'];
          };
        };
        /** @description Not found — plan, item, or invite token is invalid */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Bulk update items as a guest via invite token
     * @description Updates multiple items. No top-level status field — to update your status per item, send assignmentStatusList with your own entry: [{ participantId: "your-id", status: "purchased" }]. Backend merges into the full list for each item. Only allowed for items assigned to the guest or unassigned. Response returns each item's assignmentStatusList filtered to only your entry.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
          inviteToken: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-53'];
        };
      };
      responses: {
        /** @description All items updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-50'];
          };
        };
        /** @description Partial success — some items updated, some had validation or permission errors */
        207: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-50'];
          };
        };
        /** @description Not found — plan, item, or invite token is invalid */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user from JWT
     * @description Returns the authenticated user identity extracted from the JWT. Returns 401 if no valid JWT is provided.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Authenticated user identity */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: {
                id: string;
                email: string;
                role: string;
              };
            };
          };
        };
        /** @description JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user profile
     * @description Returns user identity from JWT and app preferences from the database. Returns 401 if no valid JWT is provided.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User identity and preferences */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-55'];
          };
        };
        /** @description JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update user preferences
     * @description Creates or updates the authenticated user's app preferences. Returns 401 if no valid JWT is provided.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-56'];
        };
      };
      responses: {
        /** @description Updated preferences */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-57'];
          };
        };
        /** @description JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
  '/auth/sync-profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sync JWT identity to all participant records
     * @description Updates all participant records linked to the authenticated user with identity fields from the JWT (name, email, phone, avatar). Call this after updating the user profile in Supabase so all plans reflect the latest data.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Number of participant records synced */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              synced: number;
            };
          };
        };
        /** @description JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}/claim/{inviteToken}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Claim a participant spot via invite token
     * @description Links an authenticated user (JWT) to an existing participant record identified by the invite token. After claiming, the user can access the plan via JWT without the invite token.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
          inviteToken: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Participant claimed successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-19'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — invite token or plan is invalid */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}/join-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request to join a plan
     * @description Creates a join request for the authenticated user. Idempotent: returns existing request if one already exists. Plan must exist and user must not already be a participant.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-33'];
        };
      };
      responses: {
        /** @description Join request already exists — returned existing */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-28'];
          };
        };
        /** @description Join request created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-28'];
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Conflict — duplicate join request */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}/join-requests/{requestId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Approve or reject a join request
     * @description Owner or admin updates a pending join request. Approved requests create a new participant linked to the requester. Rejected requests update status only.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
          requestId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-30'];
        };
      };
      responses: {
        /** @description Join request approved or rejected */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': unknown;
          };
        };
        /** @description Bad request — check the message field for details */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Authentication required — JWT token missing or invalid */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Forbidden — only the plan owner can manage requests */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Not found — plan or join request does not exist */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Conflict — request already approved or rejected */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Service temporarily unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ErrorResponse */
    'def-0': {
      message: string;
      code?: string;
    };
    /** PaginationQuery */
    'def-1': {
      /** @default 1 */
      page: number;
      /** @default 20 */
      limit: number;
    };
    /** PaginationMeta */
    'def-2': {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
    /** HealthResponse */
    'def-3': {
      /** @enum {string} */
      status: 'healthy';
      /** @enum {string} */
      database: 'connected';
    };
    /** Location */
    'def-4': {
      locationId: string;
      name: string;
      country?: string | null;
      region?: string | null;
      city?: string | null;
      latitude?: number | null;
      longitude?: number | null;
      timezone?: string | null;
    };
    /** Plan */
    'def-5': {
      /** Format: uuid */
      planId: string;
      title: string;
      description?: string | null;
      /** @enum {string} */
      status: 'draft' | 'active' | 'archived';
      /** @enum {string} */
      visibility: 'public' | 'invite_only' | 'private';
      /** Format: uuid */
      ownerParticipantId?: string | null;
      /** Format: uuid */
      createdByUserId?: string | null;
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** PlanList */
    'def-6': components['schemas']['def-5'][];
    /** PendingJoinRequestPreview */
    'def-7': {
      /** Format: uuid */
      planId: string;
      title: string;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      location?: components['schemas']['def-4'] | null;
    };
    /** PendingJoinRequestPreviewList */
    'def-8': components['schemas']['def-7'][];
    /** OwnerBody */
    'def-9': {
      name: string;
      lastName: string;
      contactPhone: string;
      displayName?: string;
      avatarUrl?: string;
      contactEmail?: string;
    };
    /** CreatePlanBody */
    'def-10': {
      title: string;
      description?: string | null;
      /** @enum {string} */
      visibility?: 'public' | 'invite_only' | 'private';
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
      owner: components['schemas']['def-9'];
      participants?: components['schemas']['def-21'][];
    };
    /** UpdatePlanBody */
    'def-11': {
      title?: string;
      description?: string | null;
      /** @enum {string} */
      status?: 'draft' | 'active' | 'archived';
      /** @enum {string} */
      visibility?: 'public' | 'invite_only' | 'private';
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
    };
    /** PlanIdParam */
    'def-12': {
      /** Format: uuid */
      planId: string;
    };
    /** DeletePlanResponse */
    'def-13': {
      ok: boolean;
    };
    /** Item */
    'def-14': {
      /** Format: uuid */
      itemId: string;
      /** Format: uuid */
      planId: string;
      name: string;
      /** @enum {string} */
      category: 'equipment' | 'food';
      quantity: number;
      /** @enum {string} */
      unit:
        | 'pcs'
        | 'kg'
        | 'g'
        | 'lb'
        | 'oz'
        | 'l'
        | 'ml'
        | 'm'
        | 'cm'
        | 'pack'
        | 'set';
      subcategory?: string | null;
      notes?: string | null;
      /** @description True when this item is assigned to all participants. When a new participant joins the plan, they are automatically added to items with this flag. */
      isAllParticipants: boolean;
      /** @description Per-participant assignment and status tracking (replaces the old top-level status field). Each entry is { participantId, status } where status is one of: pending, purchased, packed, canceled. For non-owner responses, this array is filtered to only the requesting participant's entry. */
      assignmentStatusList: {
        /** Format: uuid */
        participantId: string;
        /** @enum {string} */
        status: 'pending' | 'purchased' | 'packed' | 'canceled';
      }[];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** ItemList */
    'def-15': components['schemas']['def-14'][];
    /** CreateItemBody */
    'def-16': {
      name: string;
      /** @enum {string} */
      category: 'equipment' | 'food';
      quantity: number;
      /** @enum {string} */
      unit?:
        | 'pcs'
        | 'kg'
        | 'g'
        | 'lb'
        | 'oz'
        | 'l'
        | 'ml'
        | 'm'
        | 'cm'
        | 'pack'
        | 'set';
      subcategory?: string | null;
      notes?: string | null;
      /** @description The full list of participant assignments for this item. To assign to all participants: send every participant with status "pending" and set isAllParticipants=true. To assign a subset: send only those participants and set isAllParticipants=false (or omit it). To leave unassigned: omit this field or send []. Owner-only on create. */
      assignmentStatusList?: {
        /** Format: uuid */
        participantId: string;
        /** @enum {string} */
        status: 'pending' | 'purchased' | 'packed' | 'canceled';
      }[];
      /** @description Set true when assigning to all participants (new joiners will be auto-added). Set false or omit for subset/single/no assignment. Owner-only on create. */
      isAllParticipants?: boolean;
    };
    /** UpdateItemBody */
    'def-17': {
      name?: string;
      /** @enum {string} */
      category?: 'equipment' | 'food';
      quantity?: number;
      /** @enum {string} */
      unit?:
        | 'pcs'
        | 'kg'
        | 'g'
        | 'lb'
        | 'oz'
        | 'l'
        | 'ml'
        | 'm'
        | 'cm'
        | 'pack'
        | 'set';
      subcategory?: string | null;
      notes?: string | null;
      /** @description Owner: send the full desired assignment list. Non-owner: send only your own entry with updated status — backend merges into the full list. To toggle assign-all ON (owner): send all participants + isAllParticipants=true. To toggle assign-all OFF (owner): send [] + isAllParticipants=false. */
      assignmentStatusList?: {
        /** Format: uuid */
        participantId: string;
        /** @enum {string} */
        status: 'pending' | 'purchased' | 'packed' | 'canceled';
      }[];
      /** @description Set true to mark as assigned to all (new joiners auto-added). Set false to unmark. Only the plan owner can change this flag. */
      isAllParticipants?: boolean;
    };
    /** ItemIdParam */
    'def-18': {
      /** Format: uuid */
      itemId: string;
    };
    /** Participant */
    'def-19': {
      /** Format: uuid */
      participantId: string;
      /** Format: uuid */
      planId: string;
      /** Format: uuid */
      userId?: string | null;
      name: string;
      lastName: string;
      contactPhone: string;
      displayName?: string | null;
      /** @enum {string} */
      role: 'owner' | 'participant' | 'viewer';
      avatarUrl?: string | null;
      contactEmail?: string | null;
      inviteToken?: string | null;
      /** @enum {string} */
      inviteStatus: 'pending' | 'invited' | 'accepted';
      /** @enum {string} */
      rsvpStatus: 'pending' | 'confirmed' | 'not_sure';
      /** Format: date-time */
      lastActivityAt?: string | null;
      adultsCount?: number | null;
      kidsCount?: number | null;
      foodPreferences?: string | null;
      allergies?: string | null;
      notes?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** ParticipantList */
    'def-20': components['schemas']['def-19'][];
    /** CreateParticipantBody */
    'def-21': {
      name: string;
      lastName: string;
      contactPhone: string;
      displayName?: string;
      /** @enum {string} */
      role?: 'participant' | 'viewer';
      avatarUrl?: string;
      contactEmail?: string;
      adultsCount?: number;
      kidsCount?: number;
      foodPreferences?: string;
      allergies?: string;
      notes?: string;
    };
    /** UpdateParticipantBody */
    'def-22': {
      name?: string;
      lastName?: string;
      contactPhone?: string;
      displayName?: string | null;
      /** @enum {string} */
      role?: 'participant' | 'viewer';
      avatarUrl?: string | null;
      contactEmail?: string | null;
      adultsCount?: number | null;
      kidsCount?: number | null;
      foodPreferences?: string | null;
      allergies?: string | null;
      notes?: string | null;
      /** @enum {string} */
      rsvpStatus?: 'pending' | 'confirmed' | 'not_sure';
    };
    /** ParticipantIdParam */
    'def-23': {
      /** Format: uuid */
      participantId: string;
    };
    /** DeleteParticipantResponse */
    'def-24': {
      ok: boolean;
    };
    /** PlanWithDetails */
    'def-25': {
      /** Format: uuid */
      planId: string;
      title: string;
      description?: string | null;
      /** @enum {string} */
      status: 'draft' | 'active' | 'archived';
      /** @enum {string} */
      visibility: 'public' | 'invite_only' | 'private';
      /** Format: uuid */
      ownerParticipantId?: string | null;
      /** Format: uuid */
      createdByUserId?: string | null;
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      items: components['schemas']['def-15'];
      participants: components['schemas']['def-20'];
      joinRequests?: components['schemas']['def-32'];
    };
    /** PlanNotLoggedInResponse */
    'def-26': {
      /** @enum {string} */
      status: 'not_logged_in';
    };
    /** PlanPreviewFields */
    'def-27': {
      title: string;
      description?: string | null;
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
    };
    /** JoinRequest */
    'def-28': {
      /** Format: uuid */
      requestId: string;
      /** Format: uuid */
      planId: string;
      /** Format: uuid */
      supabaseUserId: string;
      name: string;
      lastName: string;
      contactPhone: string;
      contactEmail?: string | null;
      displayName?: string | null;
      adultsCount?: number | null;
      kidsCount?: number | null;
      foodPreferences?: string | null;
      allergies?: string | null;
      notes?: string | null;
      /** @enum {string} */
      status: 'pending' | 'approved' | 'rejected';
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** JoinRequestActionParams */
    'def-29': {
      /** Format: uuid */
      planId: string;
      /** Format: uuid */
      requestId: string;
    };
    /** UpdateJoinRequestStatusBody */
    'def-30': {
      /** @enum {string} */
      status: 'approved' | 'rejected';
    };
    /** PlanNotParticipantResponse */
    'def-31': {
      /** @enum {string} */
      status: 'not_participant';
      preview: components['schemas']['def-27'];
      joinRequest: components['schemas']['def-28'] | null;
    };
    /** JoinRequestList */
    'def-32': components['schemas']['def-28'][];
    /** CreateJoinRequestBody */
    'def-33': {
      name: string;
      lastName: string;
      contactPhone: string;
      displayName?: string;
      contactEmail?: string;
      adultsCount?: number;
      kidsCount?: number;
      foodPreferences?: string;
      allergies?: string;
      notes?: string;
    };
    /** InviteParams */
    'def-34': {
      /** Format: uuid */
      planId: string;
      inviteToken: string;
    };
    /** InviteParticipant */
    'def-35': {
      /** Format: uuid */
      participantId: string;
      displayName?: string | null;
      /** @enum {string} */
      role: 'owner' | 'participant' | 'viewer';
    };
    /** InviteParticipantList */
    'def-36': components['schemas']['def-35'][];
    /** InviteMyPreferences */
    'def-37': {
      adultsCount?: number | null;
      kidsCount?: number | null;
      foodPreferences?: string | null;
      allergies?: string | null;
      notes?: string | null;
    };
    /** InvitePlanResponse */
    'def-38': {
      /** Format: uuid */
      planId: string;
      title: string;
      description?: string | null;
      /** @enum {string} */
      status: 'draft' | 'active' | 'archived';
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      items: components['schemas']['def-15'];
      participants: components['schemas']['def-36'];
      /** Format: uuid */
      myParticipantId: string;
      /** @enum {string} */
      myRsvpStatus: 'pending' | 'confirmed' | 'not_sure';
      myPreferences: components['schemas']['def-37'];
    };
    /** RegenerateTokenParams */
    'def-39': {
      /** Format: uuid */
      planId: string;
      /** Format: uuid */
      participantId: string;
    };
    /** RegenerateTokenResponse */
    'def-40': {
      inviteToken: string;
    };
    /** UpdateInvitePreferencesBody */
    'def-41': {
      displayName?: string | null;
      adultsCount?: number | null;
      kidsCount?: number | null;
      foodPreferences?: string | null;
      allergies?: string | null;
      notes?: string | null;
      /** @enum {string} */
      rsvpStatus?: 'confirmed' | 'not_sure';
    };
    /** InvitePreferencesResponse */
    'def-42': {
      /** Format: uuid */
      participantId: string;
      displayName?: string | null;
      /** @enum {string} */
      role: 'owner' | 'participant' | 'viewer';
      /** @enum {string} */
      rsvpStatus: 'pending' | 'confirmed' | 'not_sure';
      adultsCount?: number | null;
      kidsCount?: number | null;
      foodPreferences?: string | null;
      allergies?: string | null;
      notes?: string | null;
    };
    /** InviteItemParams */
    'def-43': {
      /** Format: uuid */
      planId: string;
      inviteToken: string;
      /** Format: uuid */
      itemId: string;
    };
    /** CreateInviteItemBody */
    'def-44': {
      name: string;
      /** @enum {string} */
      category: 'equipment' | 'food';
      quantity: number;
      /** @enum {string} */
      unit?:
        | 'pcs'
        | 'kg'
        | 'g'
        | 'lb'
        | 'oz'
        | 'l'
        | 'ml'
        | 'm'
        | 'cm'
        | 'pack'
        | 'set';
      subcategory?: string | null;
      notes?: string | null;
    };
    /** UpdateInviteItemBody */
    'def-45': {
      name?: string;
      /** @enum {string} */
      category?: 'equipment' | 'food';
      quantity?: number;
      /** @enum {string} */
      unit?:
        | 'pcs'
        | 'kg'
        | 'g'
        | 'lb'
        | 'oz'
        | 'l'
        | 'ml'
        | 'm'
        | 'cm'
        | 'pack'
        | 'set';
      subcategory?: string | null;
      notes?: string | null;
      /** @description Send only your own entry with updated status. Backend merges into the full list. */
      assignmentStatusList?: {
        /** Format: uuid */
        participantId: string;
        /** @enum {string} */
        status: 'pending' | 'purchased' | 'packed' | 'canceled';
      }[];
    };
    /** BulkCreateItemBody */
    'def-46': {
      items: components['schemas']['def-16'][];
    };
    /** BulkUpdateItemEntry */
    'def-47': {
      /** Format: uuid */
      itemId: string;
      name?: string;
      /** @enum {string} */
      category?: 'equipment' | 'food';
      quantity?: number;
      /** @enum {string} */
      unit?:
        | 'pcs'
        | 'kg'
        | 'g'
        | 'lb'
        | 'oz'
        | 'l'
        | 'ml'
        | 'm'
        | 'cm'
        | 'pack'
        | 'set';
      subcategory?: string | null;
      notes?: string | null;
      /** @description Owner: send the full desired assignment list. Non-owner: send only your own entry — backend merges. Same rules as single-item PATCH. */
      assignmentStatusList?: {
        /** Format: uuid */
        participantId: string;
        /** @enum {string} */
        status: 'pending' | 'purchased' | 'packed' | 'canceled';
      }[];
      /** @description Set true to mark as assigned to all (new joiners auto-added). Set false to unmark. Owner-only. */
      isAllParticipants?: boolean;
    };
    /** BulkUpdateItemBody */
    'def-48': {
      items: components['schemas']['def-47'][];
    };
    /** BulkItemError */
    'def-49': {
      name: string;
      message: string;
    };
    /** BulkItemResponse */
    'def-50': {
      items: components['schemas']['def-15'];
      errors: components['schemas']['def-49'][];
    };
    /** BulkCreateInviteItemBody */
    'def-51': {
      items: components['schemas']['def-44'][];
    };
    /** BulkUpdateInviteItemEntry */
    'def-52': {
      /** Format: uuid */
      itemId: string;
      name?: string;
      /** @enum {string} */
      category?: 'equipment' | 'food';
      quantity?: number;
      /** @enum {string} */
      unit?:
        | 'pcs'
        | 'kg'
        | 'g'
        | 'lb'
        | 'oz'
        | 'l'
        | 'ml'
        | 'm'
        | 'cm'
        | 'pack'
        | 'set';
      subcategory?: string | null;
      notes?: string | null;
      /** @description Send only your own entry with updated status. Backend merges into the full list. */
      assignmentStatusList?: {
        /** Format: uuid */
        participantId: string;
        /** @enum {string} */
        status: 'pending' | 'purchased' | 'packed' | 'canceled';
      }[];
    };
    /** BulkUpdateInviteItemBody */
    'def-53': {
      items: components['schemas']['def-52'][];
    };
    /** UserPreferences */
    'def-54': {
      /** @description Free-text dietary preferences, e.g. "vegetarian, no shellfish" */
      foodPreferences?: string | null;
      /** @description Free-text allergy list, e.g. "nuts, gluten, dairy" */
      allergies?: string | null;
      /** @description List of equipment item names the user typically brings on trips, e.g. ["tent", "sleeping bag", "headlamp"] */
      defaultEquipment?: string[] | null;
    };
    /** ProfileResponse */
    'def-55': {
      user: {
        id: string;
        email: string;
        role: string;
      };
      /** @description App preferences for this user. Null if the user has never saved preferences. */
      preferences: components['schemas']['def-54'] | null;
    };
    /** UpdateProfileBody */
    'def-56': {
      /** @description Free-text dietary preferences, e.g. "vegetarian, no shellfish". Send null to clear. */
      foodPreferences?: string | null;
      /** @description Free-text allergy list, e.g. "nuts, gluten, dairy". Send null to clear. */
      allergies?: string | null;
      /** @description List of equipment item names the user typically brings. Send null to clear. */
      defaultEquipment?: string[] | null;
    };
    /** UpdateProfileResponse */
    'def-57': {
      preferences: components['schemas']['def-54'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
