/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Check if the server and database are healthy
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-3'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all plans
     * @description Retrieve all plans ordered by creation date
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-6'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new plan
     * @description Create a new plan with the provided details
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-7'];
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-5'];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get plan by ID
     * @description Retrieve a single plan by its ID with associated items
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-17'];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a plan
     * @description Delete a plan by its ID. Cascade delete handles related items, participants, and assignments.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-10'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans/{planId}/participants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all participants for a plan
     * @description Retrieve all participants belonging to a specific plan
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-19'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    /**
     * Add a participant to a plan
     * @description Create a new participant in the specified plan
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-20'];
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-18'];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/participants/{participantId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get participant by ID
     * @description Retrieve a single participant by its ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          participantId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-18'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a participant
     * @description Delete a participant by its ID. Items assigned to this participant will have their assignment cleared.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          participantId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-23'];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update a participant
     * @description Update an existing participant by its ID
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          participantId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-21'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-18'];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
  '/plans/{planId}/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all items for a plan
     * @description Retrieve all items belonging to a specific plan
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-12'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    /**
     * Add an item to a plan
     * @description Create a new item in the specified plan. Equipment items always use pcs as the unit. Food items require a unit.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          planId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-13'];
        };
      };
      responses: {
        /** @description Default Response */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-11'];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/items/{itemId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete an item
     * @description Delete an item by its ID. Cascade delete handles related assignments.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-16'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update an item
     * @description Update an existing item by its ID
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['def-14'];
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-11'];
          };
        };
        /** @description Default Response */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ErrorResponse */
    'def-0': {
      message: string;
      code?: string;
    };
    /** PaginationQuery */
    'def-1': {
      /** @default 1 */
      page: number;
      /** @default 20 */
      limit: number;
    };
    /** PaginationMeta */
    'def-2': {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
    /** HealthResponse */
    'def-3': {
      /** @enum {string} */
      status: 'healthy';
      /** @enum {string} */
      database: 'connected';
    };
    /** Location */
    'def-4': {
      locationId: string;
      name: string;
      country?: string | null;
      region?: string | null;
      city?: string | null;
      latitude?: number | null;
      longitude?: number | null;
      timezone?: string | null;
    };
    /** Plan */
    'def-5': {
      /** Format: uuid */
      planId: string;
      title: string;
      description?: string | null;
      /** @enum {string} */
      status: 'draft' | 'active' | 'archived';
      /** @enum {string} */
      visibility: 'public' | 'unlisted' | 'private';
      /** Format: uuid */
      ownerParticipantId?: string | null;
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** PlanList */
    'def-6': components['schemas']['def-5'][];
    /** CreatePlanBody */
    'def-7': {
      title: string;
      description?: string | null;
      /** @enum {string} */
      visibility?: 'public' | 'unlisted' | 'private';
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
    };
    /** UpdatePlanBody */
    'def-8': {
      title?: string;
      description?: string | null;
      /** @enum {string} */
      status?: 'draft' | 'active' | 'archived';
      /** @enum {string} */
      visibility?: 'public' | 'unlisted' | 'private';
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
    };
    /** PlanIdParam */
    'def-9': {
      /** Format: uuid */
      planId: string;
    };
    /** DeletePlanResponse */
    'def-10': {
      ok: boolean;
    };
    /** Item */
    'def-11': {
      /** Format: uuid */
      itemId: string;
      /** Format: uuid */
      planId: string;
      name: string;
      /** @enum {string} */
      category: 'equipment' | 'food';
      quantity: number;
      /** @enum {string} */
      unit: 'pcs' | 'kg' | 'g' | 'lb' | 'oz' | 'l' | 'ml' | 'pack' | 'set';
      /** @enum {string} */
      status: 'pending' | 'purchased' | 'packed' | 'canceled';
      notes?: string | null;
      /** Format: uuid */
      assignedParticipantId?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** ItemList */
    'def-12': components['schemas']['def-11'][];
    /** CreateItemBody */
    'def-13': {
      name: string;
      /** @enum {string} */
      category: 'equipment' | 'food';
      quantity: number;
      /** @enum {string} */
      unit?: 'pcs' | 'kg' | 'g' | 'lb' | 'oz' | 'l' | 'ml' | 'pack' | 'set';
      /** @enum {string} */
      status: 'pending' | 'purchased' | 'packed' | 'canceled';
      notes?: string | null;
      /** Format: uuid */
      assignedParticipantId?: string | null;
    };
    /** UpdateItemBody */
    'def-14': {
      name?: string;
      /** @enum {string} */
      category?: 'equipment' | 'food';
      quantity?: number;
      /** @enum {string} */
      unit?: 'pcs' | 'kg' | 'g' | 'lb' | 'oz' | 'l' | 'ml' | 'pack' | 'set';
      /** @enum {string} */
      status?: 'pending' | 'purchased' | 'packed' | 'canceled';
      notes?: string | null;
      /** Format: uuid */
      assignedParticipantId?: string | null;
    };
    /** ItemIdParam */
    'def-15': {
      /** Format: uuid */
      itemId: string;
    };
    /** DeleteItemResponse */
    'def-16': {
      ok: boolean;
    };
    /** PlanWithItems */
    'def-17': {
      /** Format: uuid */
      planId: string;
      title: string;
      description?: string | null;
      /** @enum {string} */
      status: 'draft' | 'active' | 'archived';
      /** @enum {string} */
      visibility: 'public' | 'unlisted' | 'private';
      /** Format: uuid */
      ownerParticipantId?: string | null;
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      items: components['schemas']['def-12'];
    };
    /** Participant */
    'def-18': {
      /** Format: uuid */
      participantId: string;
      /** Format: uuid */
      planId: string;
      displayName: string;
      name?: string | null;
      lastName?: string | null;
      /** @enum {string} */
      role: 'owner' | 'participant' | 'viewer';
      avatarUrl?: string | null;
      contactEmail?: string | null;
      contactPhone?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** ParticipantList */
    'def-19': components['schemas']['def-18'][];
    /** CreateParticipantBody */
    'def-20': {
      displayName: string;
      /** @enum {string} */
      role?: 'owner' | 'participant' | 'viewer';
      name?: string;
      lastName?: string;
      avatarUrl?: string;
      contactEmail?: string;
      contactPhone?: string;
    };
    /** UpdateParticipantBody */
    'def-21': {
      displayName?: string;
      /** @enum {string} */
      role?: 'owner' | 'participant' | 'viewer';
      name?: string | null;
      lastName?: string | null;
      avatarUrl?: string | null;
      contactEmail?: string | null;
      contactPhone?: string | null;
    };
    /** ParticipantIdParam */
    'def-22': {
      /** Format: uuid */
      participantId: string;
    };
    /** DeleteParticipantResponse */
    'def-23': {
      ok: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
