/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Check if the server and database are healthy
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-3'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/plans': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all plans
     * @description Retrieve all plans ordered by creation date
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-6'];
          };
        };
        /** @description Default Response */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
        /** @description Default Response */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['def-0'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ErrorResponse */
    'def-0': {
      message: string;
      code?: string;
    };
    /** PaginationQuery */
    'def-1': {
      /** @default 1 */
      page: number;
      /** @default 20 */
      limit: number;
    };
    /** PaginationMeta */
    'def-2': {
      page: number;
      limit: number;
      total: number;
      totalPages: number;
    };
    /** HealthResponse */
    'def-3': {
      /** @enum {string} */
      status: 'healthy';
      /** @enum {string} */
      database: 'connected';
    };
    /** Location */
    'def-4': {
      locationId: string;
      name: string;
      country?: string | null;
      region?: string | null;
      city?: string | null;
      latitude?: number | null;
      longitude?: number | null;
      timezone?: string | null;
    };
    /** Plan */
    'def-5': {
      /** Format: uuid */
      planId: string;
      title: string;
      description?: string | null;
      /** @enum {string} */
      status: 'draft' | 'active' | 'archived';
      /** @enum {string} */
      visibility: 'public' | 'unlisted' | 'private';
      /** Format: uuid */
      ownerParticipantId?: string | null;
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** PlanList */
    'def-6': components['schemas']['def-5'][];
    /** CreatePlanBody */
    'def-7': {
      title: string;
      description?: string | null;
      /** @enum {string} */
      visibility?: 'public' | 'unlisted' | 'private';
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
    };
    /** UpdatePlanBody */
    'def-8': {
      title?: string;
      description?: string | null;
      /** @enum {string} */
      status?: 'draft' | 'active' | 'archived';
      /** @enum {string} */
      visibility?: 'public' | 'unlisted' | 'private';
      location?: components['schemas']['def-4'] | null;
      /** Format: date-time */
      startDate?: string | null;
      /** Format: date-time */
      endDate?: string | null;
      tags?: string[] | null;
    };
    /** PlanIdParam */
    'def-9': {
      /** Format: uuid */
      planId: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
