/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

import { Route as rootRouteImport } from './routes/__root';
import { Route as CreatePlanRouteImport } from './routes/create-plan';
import { Route as PlanPlanIdRouteImport } from './routes/plan.$planId';

const SignupLazyRouteImport = createFileRoute('/signup')();
const SigninLazyRouteImport = createFileRoute('/signin')();
const PlansLazyRouteImport = createFileRoute('/plans')();
const NotFoundLazyRouteImport = createFileRoute('/not-found')();
const CompleteProfileLazyRouteImport = createFileRoute('/complete-profile')();
const AboutLazyRouteImport = createFileRoute('/about')();
const IndexLazyRouteImport = createFileRoute('/')();

const SignupLazyRoute = SignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route));
const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route));
const PlansLazyRoute = PlansLazyRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/plans.lazy').then((d) => d.Route));
const NotFoundLazyRoute = NotFoundLazyRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/not-found.lazy').then((d) => d.Route));
const CompleteProfileLazyRoute = CompleteProfileLazyRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/complete-profile.lazy').then((d) => d.Route)
);
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route));
const CreatePlanRoute = CreatePlanRouteImport.update({
  id: '/create-plan',
  path: '/create-plan',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route));
const PlanPlanIdRoute = PlanPlanIdRouteImport.update({
  id: '/plan/$planId',
  path: '/plan/$planId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/plan.$planId.lazy').then((d) => d.Route));

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute;
  '/create-plan': typeof CreatePlanRoute;
  '/about': typeof AboutLazyRoute;
  '/complete-profile': typeof CompleteProfileLazyRoute;
  '/not-found': typeof NotFoundLazyRoute;
  '/plans': typeof PlansLazyRoute;
  '/signin': typeof SigninLazyRoute;
  '/signup': typeof SignupLazyRoute;
  '/plan/$planId': typeof PlanPlanIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute;
  '/create-plan': typeof CreatePlanRoute;
  '/about': typeof AboutLazyRoute;
  '/complete-profile': typeof CompleteProfileLazyRoute;
  '/not-found': typeof NotFoundLazyRoute;
  '/plans': typeof PlansLazyRoute;
  '/signin': typeof SigninLazyRoute;
  '/signup': typeof SignupLazyRoute;
  '/plan/$planId': typeof PlanPlanIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexLazyRoute;
  '/create-plan': typeof CreatePlanRoute;
  '/about': typeof AboutLazyRoute;
  '/complete-profile': typeof CompleteProfileLazyRoute;
  '/not-found': typeof NotFoundLazyRoute;
  '/plans': typeof PlansLazyRoute;
  '/signin': typeof SigninLazyRoute;
  '/signup': typeof SignupLazyRoute;
  '/plan/$planId': typeof PlanPlanIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/create-plan'
    | '/about'
    | '/complete-profile'
    | '/not-found'
    | '/plans'
    | '/signin'
    | '/signup'
    | '/plan/$planId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/create-plan'
    | '/about'
    | '/complete-profile'
    | '/not-found'
    | '/plans'
    | '/signin'
    | '/signup'
    | '/plan/$planId';
  id:
    | '__root__'
    | '/'
    | '/create-plan'
    | '/about'
    | '/complete-profile'
    | '/not-found'
    | '/plans'
    | '/signin'
    | '/signup'
    | '/plan/$planId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  CreatePlanRoute: typeof CreatePlanRoute;
  AboutLazyRoute: typeof AboutLazyRoute;
  CompleteProfileLazyRoute: typeof CompleteProfileLazyRoute;
  NotFoundLazyRoute: typeof NotFoundLazyRoute;
  PlansLazyRoute: typeof PlansLazyRoute;
  SigninLazyRoute: typeof SigninLazyRoute;
  SignupLazyRoute: typeof SignupLazyRoute;
  PlanPlanIdRoute: typeof PlanPlanIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/signin': {
      id: '/signin';
      path: '/signin';
      fullPath: '/signin';
      preLoaderRoute: typeof SigninLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/plans': {
      id: '/plans';
      path: '/plans';
      fullPath: '/plans';
      preLoaderRoute: typeof PlansLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/not-found': {
      id: '/not-found';
      path: '/not-found';
      fullPath: '/not-found';
      preLoaderRoute: typeof NotFoundLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/complete-profile': {
      id: '/complete-profile';
      path: '/complete-profile';
      fullPath: '/complete-profile';
      preLoaderRoute: typeof CompleteProfileLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/create-plan': {
      id: '/create-plan';
      path: '/create-plan';
      fullPath: '/create-plan';
      preLoaderRoute: typeof CreatePlanRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/plan/$planId': {
      id: '/plan/$planId';
      path: '/plan/$planId';
      fullPath: '/plan/$planId';
      preLoaderRoute: typeof PlanPlanIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CreatePlanRoute: CreatePlanRoute,
  AboutLazyRoute: AboutLazyRoute,
  CompleteProfileLazyRoute: CompleteProfileLazyRoute,
  NotFoundLazyRoute: NotFoundLazyRoute,
  PlansLazyRoute: PlansLazyRoute,
  SigninLazyRoute: SigninLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
  PlanPlanIdRoute: PlanPlanIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
