/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

import { Route as rootRouteImport } from './routes/__root';

const PlansLazyRouteImport = createFileRoute('/plans')();
const AboutLazyRouteImport = createFileRoute('/about')();
const IndexLazyRouteImport = createFileRoute('/')();
const PlanPlanIdLazyRouteImport = createFileRoute('/plan/$planId')();

const PlansLazyRoute = PlansLazyRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/plans.lazy').then((d) => d.Route));
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route));
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route));
const PlanPlanIdLazyRoute = PlanPlanIdLazyRouteImport.update({
  id: '/plan/$planId',
  path: '/plan/$planId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/plan.$planId.lazy').then((d) => d.Route));

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute;
  '/about': typeof AboutLazyRoute;
  '/plans': typeof PlansLazyRoute;
  '/plan/$planId': typeof PlanPlanIdLazyRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute;
  '/about': typeof AboutLazyRoute;
  '/plans': typeof PlansLazyRoute;
  '/plan/$planId': typeof PlanPlanIdLazyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexLazyRoute;
  '/about': typeof AboutLazyRoute;
  '/plans': typeof PlansLazyRoute;
  '/plan/$planId': typeof PlanPlanIdLazyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/about' | '/plans' | '/plan/$planId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/about' | '/plans' | '/plan/$planId';
  id: '__root__' | '/' | '/about' | '/plans' | '/plan/$planId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  AboutLazyRoute: typeof AboutLazyRoute;
  PlansLazyRoute: typeof PlansLazyRoute;
  PlanPlanIdLazyRoute: typeof PlanPlanIdLazyRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plans': {
      id: '/plans';
      path: '/plans';
      fullPath: '/plans';
      preLoaderRoute: typeof PlansLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/plan/$planId': {
      id: '/plan/$planId';
      path: '/plan/$planId';
      fullPath: '/plan/$planId';
      preLoaderRoute: typeof PlanPlanIdLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  PlansLazyRoute: PlansLazyRoute,
  PlanPlanIdLazyRoute: PlanPlanIdLazyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
